import 'package:flutter/material.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedContinueWidget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedLine8Widget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedGenderWidget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedRectangle14Widget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedBasicinfoWidget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedBirthdayWidget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedEmailWidget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedLine7Widget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/munzapp/generatedgenderdateofbirthwidget/generated/GeneratedLine5Widget.dart';

/* Frame Gender & Date of birth
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGenderDateofbirthWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 414.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 33, 33, 33),
                ),
              ),
              Positioned(
                left: 41.0,
                top: 667.0,
                right: null,
                bottom: null,
                width: 320.0,
                height: 59.0,
                child: GeneratedRectangle14Widget(),
              ),
              Positioned(
                left: 129.0,
                top: 74.0,
                right: null,
                bottom: null,
                width: 352.0,
                height: 228.0,
                child: GeneratedBasicinfoWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 159.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 33.0,
                child: GeneratedNameWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 215.0,
                right: null,
                bottom: null,
                width: 332.0135498046875,
                height: 1.0,
                child: GeneratedLine4Widget(),
              ),
              Positioned(
                left: 11.0,
                top: 243.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 33.0,
                child: GeneratedBirthdayWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 299.0,
                right: null,
                bottom: null,
                width: 332.0135498046875,
                height: 1.0,
                child: GeneratedLine5Widget(),
              ),
              Positioned(
                left: -3.0,
                top: 325.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 33.0,
                child: GeneratedEmailWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 380.0,
                right: null,
                bottom: null,
                width: 332.0135498046875,
                height: 1.0,
                child: GeneratedLine6Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 406.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 33.0,
                child: GeneratedPasswordWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 461.0,
                right: null,
                bottom: null,
                width: 332.0135498046875,
                height: 1.0,
                child: GeneratedLine7Widget(),
              ),
              Positioned(
                left: 7.0,
                top: 496.0,
                right: null,
                bottom: null,
                width: 168.0,
                height: 33.0,
                child: GeneratedGenderWidget(),
              ),
              Positioned(
                left: 54.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 332.0135498046875,
                height: 1.0,
                child: GeneratedLine8Widget(),
              ),
              Positioned(
                left: 160.0,
                top: 679.0,
                right: null,
                bottom: null,
                width: 99.0,
                height: 41.0,
                child: GeneratedContinueWidget(),
              )
            ]),
      ),
    ));
  }
}
